on:
  release:
    types: [created]

jobs:
  release-windows:
    name: Release Windows Binaries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows]
        goarch: ["386", amd64]
    steps:
    - uses: actions/checkout@v2
    - name: extract tag name
      shell: bash
      run: echo "TAG_NAME=$(echo ${GITHUB_REF#refs/tags/})" >> $GITHUB_ENV
    - uses: wangyoucao577/go-release-action@v1.22
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.17
        ldflags: -X main.version=${{ env.TAG_NAME }}
        extra_files: LICENSE README.md
